name: maps
description: Traker for maps

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^14.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.4
  google_polyline_algorithm: ^3.1.0
  icons_launcher: ^2.0.4
  loading_progress_indicator: ^0.1.5
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/logo_app.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

assets:
  - assets/icon/logo_app.png
