name: maps
description: Traker for maps

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3

  flutter:
    sdk: flutter

  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  google_maps_flutter: ^2.1.4
  google_polyline_algorithm: ^3.1.0

  animate_do: ^3.0.2
  icons_launcher: ^2.0.4
  loading_progress_indicator: ^0.1.5

  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/logo_app.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

assets:
  - assets/icon/logo_app.png
