name: maps
description: Traker for maps

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animate_do: ^2.1.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.5.3+1
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.4
  google_polyline_algorithm: ^3.1.0
  icons_launcher: ^1.1.7
  loading_progress_indicator: ^0.1.5
  permission_handler: ^9.2.0
  splash_screen_view: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/icon/logo_app.png'
  ios: true
  android: true

flutter:
  uses-material-design: true

assets:
  - assets/icon/logo_app.png

splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.
  color: '#ffffff'
  # background_image: "assets/icon/logo_app.png"
  # Optional parameters are listed below.
  image: assets/icon/logo_app.png
  # color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  # android: true
  # ios: true
  #web: false
  # android_gravity: center
  # ios_content_mode: center
  #web_image_mode: center
  # fullscreen: true
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
